### ISSUE TITLE
Help required to run simulator application and subscribe to data change events

### ISSUE THREAD

**Issue by vikramtamboli** [MileBuurmeijer/OPCUA-Player#4]
**Asset File**

AssetID;AssetName;MeasurementPointID;MeasurementPointName;PhysicalQuantity;Unit of Measure;Prefix;AccesRights
1001;Switch123A;1;MotorCurrent;Current;Ampere;NoPrefix;Read
1001;Switch123A;2;ControlSignalRight;NoQuantity;NoUoM;NoPrefix;Read
1001;Switch123A;3;ControlSignalLeft;NoQuantity;NoUoM;NoPrefix;Read
1001;Switch123A;4;StatusSignalRight;NoQuantity;NoUoM;NoPrefix;Read
1001;Switch123A;5;StatusSignalLeft;NoQuantity;NoUoM;NoPrefix;Read
1001;Switch123A;6;StatusSignalSection;NoQuantity;NoUoM;NoPrefix;Read

**Data File**

Asset_ID;Sensor_ID;Timestamp;Value
1001;1;2019-04-25 11:26:01.000;0.0
1001;1;2019-04-25 11:26:02.000;2.0
1001;1;2019-04-25 11:26:03.000;3.0
1001;1;2019-04-25 11:26:04.000;4.0
1001;1;2019-04-25 11:26:05.000;5.0
1001;1;2019-04-25 11:26:06.000;6.0
1001;1;2019-04-25 11:26:07.000;7.0
1001;1;2019-04-25 11:26:08.000;8.0
1001;1;2019-04-25 11:26:09.000;9.0
1001;1;2019-04-25 11:26:10.000;10.0
1001;1;2019-04-25 11:26:11.000;11.0
1001;1;2019-04-25 11:26:12.000;12.0
1001;1;2019-04-25 11:26:13.000;13.0
1001;1;2019-04-25 11:26:14.000;14.0
1001;1;2019-04-25 11:26:15.000;15.0
1001;1;2019-04-25 11:26:16.000;16.0
1001;1;2019-04-25 11:26:17.000;17.0
1001;1;2019-04-25 11:26:18.000;18.0
1001;1;2019-04-25 11:26:18.000;18.0
1001;1;2019-04-25 11:26:19.000;19.0
1001;1;2019-04-25 11:26:20.000;20.0

**Python opcua-client**
![image](https://user-images.githubusercontent.com/16055034/56721716-13048f80-6763-11e9-9108-fa56c6a02dbd.png)

We start playback by calling function

![image](https://user-images.githubusercontent.com/16055034/56721949-a5a52e80-6763-11e9-96da-8fca89963421.png)

**OPC UA Player application logs**

1. Apr 25, 2019 2:07:34 PM name.buurmeijermile.opcuaservices.controllableplayer.measurements.DataBackendController setCommand
INFO: Command Play led to runstate PlayForward 

2. Apr 25, 2019 2:07:35 PM name.buurmeijermile.opcuaservices.controllableplayer.measurements.DataStreamController openFile
INFO: File PlayerDemoData.csv opened

Here we are unable to subscribe to data change event
![image](https://user-images.githubusercontent.com/16055034/56725312-426aca80-676a-11e9-9198-a8268a375516.png)

We are not sure whether the issue is with server or client
Could you help us to get the events in client application.

**Comment by MileBuurmeijer** [comment]
Thank you for reporting this issue. This is my fault. I have forgotten to mention the user accounts that should be used to connect to the OPC UA Player service. It is username: "user" and password: "8h5%32@!~". Check the code in [OPCUAPlayerServer.java](https://github.com/MileBuurmeijer/OPCUA-Player/blob/master/src/main/java/name/buurmeijermile/opcuaservices/controllableplayer/server/OPCUAPlayerServer.java). I will update the readme to correct this omission.
